version: '2'

services:
  web:
    image: vaultwarden/server
    restart: always
    environment:
      ADMIN_TOKEN: <SECRET_TOKEN>
    ports:
      - "127.0.0.1:3005:80"
    volumes:
      - vaultwarden:/data

volumes:
  vaultwarden: