version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=<SECRET_PASSWORD>
      - POSTGRES_DB=gitea
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    image: gitea/gitea
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=<SECRET_PASSWORD>
    ports:
      - "127.0.0.1:3002:3000"
    depends_on:
      - db
    links:
      - db:db
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

volumes:
  gitea:
  postgres:
